### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [ivoleitao/stash#2]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:stash`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by ivoleitao** [comment]
Hi @IchordeDionysos,

Yes I'm thinking on doing this soon. Are you only dependent on the stash package or also on the specific implementations (disk, moor and so on) ?

I haven't migrated because there are some specific implementations (stash_dio for example) whose dependencies are not migrated yet. However I can do the migration for the ones whose dependencies are already migrated.

**Comment by IchordeDionysos** [comment]
Hey @ivoleitao,
Ahh, I see `dio` is not yet migrated, actually another package we use also is blocked by `dio` ...

I just wanted to open an issue here to make sure to keep track of it 👍

Also really appreciate your responsiveness and stash overall the package is so well built. Provides real value 💪

**Comment by ivoleitao** [comment]
Thanks for the feedback @IchordeDionysos. I intend to start the migration soon, I will not wait for dio.

**Comment by IchordeDionysos** [comment]
@ivoleitao Ahh the null safe version was merged to master yesterday, however no new version is published yet 🤔

**Comment by ivoleitao** [comment]
Hi, dio was published this weekend. I also managed to publish a null safe version of the following packages:

- stash
- stash_disk
- stash_sembast
- stash_dio
- stash_hive

stash_moor will need to wait there's third party dependencies (dev dependencies) not yet migrated
