### ISSUE TITLE
pub get doesn't resolve 1.0.4

### ISSUE THREAD

**Issue by robertflesch** [ivoleitao/stash#21]
I have been avoiding upgrading for flutter 2.0 because the one time I tried, it was a nightmare. So until I have time I have been sticking with 1.22.6

So I want to use Stash! When I add 
stash_memory: ^1.0.4
when I do a pub get, it gives me error
Because XXX depends on stash_memory ^1.0.4 which doesn't match any versions, version solving failed.
pub get failed (1; Because XXX depends on stash_memory ^1.0.4 which doesn't match any versions, version solving failed.)
However I can download 1.0.4
Is there anyway to manually import it? Or some other solution other than spending a week upgrading to flutter 2.x

**Comment by ivoleitao** [comment]
Hello,

That version does not exist, take a look at [this](https://pub.dev/packages/stash_memory/versions) link.

Actually on that version memory storage was inside the stash package. When I separated it from the main package I provided a null safe version out of the box. stash 1.0.4 is not null safe
