### ISSUE TITLE
Example Eviction Policies

### ISSUE THREAD

**Issue by muhammadsaddamnur** [ivoleitao/stash#26]
Hi this is not bug, i just confused about Eviction Policies 😅
Can you give me example for how to using Eviction Policies ?
I want to using FifoEvictionPolicy and then i have added FifoEvictionPolicy in evictionPolicy parameter, but is not work. 
Thanks

**Comment by ivoleitao** [comment]
Hi, you need to set the maxEntries or the eviction is not activated, see an example [here](https://github.com/ivoleitao/stash/blob/571249eadd7b3f987bfb9e99ad3f46a7ea6e082a/packages/stash_test/lib/src/harness/cache_harness.dart#L629) on the test harness

I believe this is documented as well in this documentation paragraph:
* `Note that the eviction policy is only applied if maxEntries is specified`
