### ISSUE TITLE
Pocketbase Support?

### ISSUE THREAD

**Issue by topcheese** [ivoleitao/stash#37]
Hi, I just discovered your package and I'm planning to use it for my project.  I also just discovered Pocketbase, and I think I'd also like to use that.  I just looked at that package, but I shouldn't have any serious problems using it with Stash as a backend?
https://pub.dev/packages/pocketbase

**Comment by ivoleitao** [comment]
Well it depends on what you want to do exactly. Stash was designed to be used as a complement to the main metadata of your app. Most of the times using stash as a local cache or repo for key values of your app is the scenario.

However it was not designed to interact remotely with an API although it's perfectly possible. However I'm not sure if that's what you are asking to be honest
