### ISSUE TITLE
Incompatible API change

### ISSUE THREAD

**Issue by RickPoleshuck** [ivoleitao/stash#38]
The cache method of the FileCacheStore object was removed between version 4.3.2 and version 4.3.3.
Also, the documentation and examples don't seem to reflect this change.

I expect changes to a module's interface such as this to require a change to the major portion of the version number. 

This is from https://semver.org/ 

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backwards compatible manner
PATCH version when you make backwards compatible bug fixes

**Comment by ivoleitao** [comment]
Yes, you are right, this is accomplished through an extension method but I completely forgot that you can hold on to a variable of other type that was the previous target of the extensions.

I will fix this in a new release ASAP

**Comment by ivoleitao** [comment]
Fixed in version 4.3.4. Sorry for the inconvenience.
