### ISSUE TITLE
TypeError in Hive vault when switching from version 4.5.2 to 5.1.0

### ISSUE THREAD

**Issue by stevsimo** [ivoleitao/stash#70]
**Describe the bug**
If you store a String value into a hive vault in version 4.5.2 and want to retrieve it in version 5.1.0 a TypeError occurs when the value is decoded in file 'packages/stash/lib/src/api/store.dart'

**To Reproduce**
1. Setup a simple vault in version 4.5.2
2. Store a String value in that vault
3. Update stash to newest version 5.1.0 in pubspec.yaml
4. Run app again and try to retrieve value from vault

Here is a simple [Example](https://github.com/coodoo-io/stash-bug)

**Expected behaviour**
Expected behaviour is that value is retrieved without errors.

**Screenshots**
![Screenshot 2024-04-11 at 15 14 33](https://github.com/ivoleitao/stash/assets/47678184/e41a3dfc-5369-498b-be99-907232ed7a39)

**Version**
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"

**Comment by stevsimo** [comment]
I opened a pull request #71

**Comment by ivoleitao** [comment]
This is a bit weird, just checked and this scenario is part of the integration tests, actually I test all the base types so not sure how this could be happening to you. Are you overriding the hive version in some way ?

**Comment by ivoleitao** [comment]
Fixed in the 5.1.1 of stash and 5.1.2 of stash_hive. Thanks for spotting this, it was a tricky one @stevsimo. I will use this opportunity to update a bunch of dependencies on a followup version please choose the best version to you. Either this one or the follow up ones
